#!/usr/bin/env Rscript --vanilla

# PURPOSE: To run CyTOF workflow (Robinson's) version 3. This script plots
# figures related to cluster merging and annotation.
# PUBLICATION: https://f1000research.com/articles/6-748

# Read command line arguments passed to the script. 
cmd_args = commandArgs(trailingOnly=TRUE)

# Temp. If using RStudio.
# setwd("/Users/farmerr2/locus/sandbox/projects/mini")


# Read yaml file. 
suppressMessages(library(yaml))
if(interactive()){
        cat("Running in interactive mode.\n")
        yam <- read_yaml("meta/pheno_noqc_20_10k.yaml", fileEncoding = "UTF-8") # Change yaml file for interactive execution.
}else{
        cat("Running in Rscript mode.\n")
        if (length(cmd_args) < 1){
        cat("Missing command line argument(s).\n")
        cat("Usage: script.R name.yaml\n")
        stopifnot(length(cmd_args) > 1)
        }else{
                yam <- read_yaml(cmd_args[1], fileEncoding = "UTF-8") # Pass yaml file as a command line argument.
        }
}

analysis_name <- yam$analysis_name
data_location <- yam$data_location
args_file <- yam$args_file
panel_file <- yam$panel_file
condition_levels <- yam$condition_levels
no_of_clusters <- yam$no_of_clusters
tsne_no_cells <- yam$tsne_no_cells
umap_no_cells <- yam$umap_no_cells
meta_string <- yam$meta_string
merging1_file  <- yam$merging1_file
# color_conditions <- yam$color_conditions

# Load external libraries.
cat("Loading external libraries.\n")
suppressMessages(library(cytofWorkflow))
suppressMessages(library(logging))
suppressMessages(library(readr))
suppressMessages(library(ggplot2))

# LOGGING
log_file <- file.path("logs", paste(analysis_name, ".log", sep = ""))
basicConfig(level='FINEST')
addHandler(writeToFile, file=log_file, level='DEBUG')

# Assigning results folders (make sure that the script1 is executed before.)
results_folder <- file.path("results", analysis_name)
figures_folder <- file.path("figures", analysis_name)

# Load daFrame with dimensionality reduction results saved in script4.
loginfo("Loading daFrame with dimensionality reduction results saved in script4.")
daf <- readRDS(file.path(results_folder, "daf_dr.rds"))

# Load cluter merging inforamtion.
merging_table1 <- suppressMessages(read_tsv(file.path("meta", merging1_file)))

# convert to factor with merged clusters in desired order.
# I am not defining factor levels here, see paper.
merging_table1$new_cluster <- factor(merging_table1$new_cluster, levels = unique(merging_table1$new_cluster))

daf <- mergeClusters(daf, k = meta_string, table = merging_table1, id = "merging1")
# Save daFrame 
loginfo("Saving daFrame with merging1 data.")
saveRDS(daf, file.path(results_folder, "daf_merging1.rds"))
loginfo("Done")

# Figure 15. UMAP plot for, where cells are colored according to the manual
# merging of the [n] cell populations, obtained with FlowSOM, into [n] cell populations.
loginfo("Generating figure 15.")
fig15 <- plotDR(daf, "UMAP", color_by = "merging1")
ggsave("figure15.pdf", plot = fig15, device = "pdf", path = figures_folder, width = 11, height = 8.5, units = "in", scale = 1)
rm(fig15)
gc()

# Figure 16. Heatmap as in Figure 6, where the additional color bar on the 
# left indicates how the [n] metaclusters, obtained with FlowSOM, are merged 
# into the [n] cell populations.
loginfo("Generating figure 16.")
pdf(file = file.path(figures_folder, "figure16.pdf"), width = 8.5, height = 11)
fig16 <- plotClusterHeatmap(daf, k = meta_string, m = "merging1")
dev.off()
rm(fig16)
gc()

# Figure 17. Heatmap of the median marker intensities of the [n] lineage 
# markers in the [n] cell populations obtained by manual merging of the 
# [n] metaclusters generated by FlowSOM.
loginfo("Generating figure 17.")
pdf(file = file.path(figures_folder, "figure17.pdf"), width = 8.5, height = 11)
fig17 <- plotClusterHeatmap(daf, k = "merging1")
dev.off()
rm(fig17)
gc()

# Figure 18. The delta area plot generated in the metaclustering step
# by the ConsensusClusterPlus function.
loginfo("Generating figure 18.")
fig18 <- metadata(daf)$delta_area
ggsave("figure18.pdf", plot = fig18, device = "pdf", path = figures_folder, width = 11, height = 8.5, units = "in", scale = 1)
rm(fig18)
gc()

loginfo("Done")
